[package]
name = "voidmic_core"
version = "0.1.0"
edition = "2021"

[dependencies]
nnnoiseless = "0.5.1"
webrtc-vad = "0.4"
biquad = "0.4"
spectrum-analyzer = "1.7.0"
aec3 = "0.1.3"
anyhow = "1.0"
log = "0.4"
crossbeam-channel = "0.5.15"
